# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
fos_ck_editor:
    configs:
        main_config:
            allowedContent: true #dont remove our custom css
            language: "fr"
            toolbar: "full"
            extraPlugins : 'codesnippet'
            filebrowserBrowseRoute: elfinder
            filebrowserBrowseRouteParameters: []
            config.allowedContent : true;
            full.insert:  "CodeSnippet"

