# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
fos_ck_editor:
    configs:
        main_config:
            allowedContent: true #dont remove our custom css
            language: "fr"
            toolbar:
                - { name: "styles", items: ['Bold', 'Italic', 'Underline', 'Strike', 'Blockquote', '-', 'Link', '-', 'RemoveFormat', '-', 'NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock', '-', 'Image', 'Table', '-', 'Styles', 'Format','Font','FontSize', '-', 'TextColor', 'BGColor', 'Source'] }
            filebrowserBrowseRoute: elfinder
            filebrowserBrowseRouteParameters: []
#    styles:
#        my_styles:
#            - { name: "Blue Title", element: "h2", styles: { color: "Blue" }}
#            - { name: "CSS Style", element: "span", attributes: { class: "my_style" }}
#            - { name: "Widget Style", type: widget, widget: "my_widget", attributes: { class: "my_widget_style" }}
