fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
#index:
#    path: /
#    controller: App\Controller\DefaultController::index
#page_show2:
#    path:       /{URL}
#    controller: App\Controller\PageController::index
#    defaults:
#        page: 1
#    requirements:
#        page: '[^/]++'